# Generated by Django 5.2.6 on 2025-09-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='is_puplished',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='titel',
            new_name='title',
        ),
    ]
