# Generated by Django 5.2.6 on 2025-09-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_is_puplished_survey_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_published',
        ),
    ]
