# Generated by Django 5.2.6 on 2025-11-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_alter_multichoicequestion_the_minimum_number_of_options_to_be_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertquestion',
            name='scale_max',
        ),
    ]
