# Generated by Django 5.2.6 on 2026-01-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_alter_matrixquestion_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.question')),
                ('range_min', models.IntegerField(default=1)),
                ('range_max', models.IntegerField(default=5)),
                ('min_label', models.CharField(blank=True, max_length=50, null=True)),
                ('max_label', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('survey.question',),
        ),
    ]
