# Generated by Django 5.2.6 on 2026-01-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_alter_question_options'),
        ('survey', '0036_sectionheader'),
    ]

    operations = [
    ]
