# Generated by Django 5.2.6 on 2026-01-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_merge_0034_alter_question_options_0036_sectionheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='section',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
